apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.notification.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.notification.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-container
        image: {{ .Values.notification.image }}
        imagePullPolicy: IfNotPresent
        env:
        # CAMBIO AQUÍ: Ahora apunta a .Values.kafka en la raíz
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.kafka.serviceName }}:{{ .Values.kafka.port }}"
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: {{ .Values.notification.groupId | quote }}
        ports:
        - containerPort: {{ .Values.notification.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notification.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: {{ .Values.notification.port }}
      targetPort: {{ .Values.notification.port }}