apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.infrastructure.postgres.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.infrastructure.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.infrastructure.postgres.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: {{ .Values.infrastructure.postgres.db }}
        - name: POSTGRES_USER
          value: {{ .Values.infrastructure.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.infrastructure.postgres.pass }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script-volume
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infrastructure.postgres.host }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432